[package]
name = "dialog"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.1", features = ["rt-multi-thread", "macros"] }
rusqlite = { version = "0.32.1", features = ["bundled"] }
scylla = "0.3.1"
colored = "2.0"
